name: Push

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r src/app/requirements.txt

      - run: |
          pip install pytest ruff streamlit

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./src/app"

      - run: |
          python -m pytest src/app/tests -v
